# for each folder in ultramarine/
# generate a new workflow for each folder in ultramarine/
name: Mass Rebuild
on:
  workflow_dispatch:

jobs:
  manifest:
    runs-on: ubuntu-latest

    outputs:
      build_matrix: ${{ steps.generate_build_matrix.outputs.build_matrix }}
      is_empty: ${{ steps.generate_build_matrix.outputs.is_empty }}

    # check out the repo
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - run: git fetch
      #- run: git checkout HEAD^

      - name: Generate Build matrix
        id: generate_build_matrix
        # generate build matrix by checking out changes in ultramarine/
        run: |
          build_matrix=$(find ultramarine/ | grep -oP 'ultramarine\/(.+)\/' | sort -u | jq -R -s -c 'split("\n")[:-1]')
          # create build matrix with { changed_folders: [ "folder1", "folder2" ] }

          echo "::set-output name=build_matrix::$build_matrix"
  build:
    needs: manifest
    strategy:
      matrix:
        pkg: ${{ fromJson(needs.manifest.outputs.build_matrix) }}
        version: ["38"]
        arch: ["x86_64", "aarch64"]
      fail-fast: false
    #if: ${{ matrix.changed_folders != '' }}
    runs-on: ${{ matrix.arch == 'aarch64' && 'ARM64' || 'ubuntu-latest' }}
    container:
      image: registry.fedoraproject.org/fedora:${{ matrix.version }}
      options: --cap-add=SYS_ADMIN --privileged
    steps:
      - name: Install repositories
        run: |
          sudo dnf install -y dnf-plugins-core
          sudo dnf config-manager --add-repo https://github.com/andaman-common-pkgs/subatomic-repos/raw/main/um${{ matrix.version }}.repo
          sudo dnf install -y ultramarine-mock-configs subatomic-cli anda mock rpm-build

      - uses: andaman-common-pkgs/anda-build@main
        if: ${{ !fromJson(needs.manifest.outputs.is_empty) }}
        with:
          name: "${{ matrix.pkg }}pkg"
          mockConfig: ultramarine-${{ matrix.version }}-${{ matrix.arch }}
          andaRepo: https://github.com/andaman-common-pkgs/subatomic-repos/raw/main/terra${{ matrix.version }}.repo

      - name: Install Subatomic client
        run: sudo dnf install -y subatomic-cli

      - name: Upload packages to subatomic
        if: ${{ !fromJson(needs.manifest.outputs.is_empty) }}
        run: |
          subatomic-cli upload --prune \
            --server https://subatomic.fyralabs.com \
            --token ${{ secrets.SUBATOMIC_TOKEN }} \
            um${{ matrix.version }} anda-build/rpm/rpms/*
